exclude: ^docs/conf.py
repos:
- hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - args:
    - --fix=lf
    id: mixed-line-ending
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
- hooks:
  - args:
    - --in-place
    - --remove-all-unused-imports
    - --remove-unused-variables
    id: autoflake
  repo: https://github.com/myint/autoflake
  rev: v2.2.1
- hooks:
  - id: isort
  repo: https://github.com/pycqa/isort
  rev: 5.13.2
- hooks:
  - id: black
    language_version: python3
  repo: https://github.com/psf/black
  rev: 24.2.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.13.0
